### ISSUE TITLE
Could not init video renderer

### ISSUE THREAD

**Issue by ril3y** [rahul-thakoor/balena-rpiplay#14]
I am using balen fleet os for the first time and its great!  However trying to run the rpiplay app I get this error in the logs when starting:

https://photos.app.goo.gl/872w6SgxtfpWYH6R7

This is a screen shot of what I am experiencing.  This is a clean install running Raspberry Pi 4.

**Comment by rahul-thakoor** [comment]
Hello @ril3y  can you please make sure you use at least `256` MB for gpu? You can set this in the fleet configuration page. 

![image](https://user-images.githubusercontent.com/13220877/142366444-34de8900-c3b8-4dd2-adfc-a414949b81bd.png)
