### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by pro-sumer** [rahul-thakoor/balena-rpiplay#16]
Nice project!

Hope I can get it to work on one of my Raspberry Pi's (currently tying wired on a 3B), but I don't see my Pi as an AirPlay receiver. Instead I see this error (repeating over and over again) on my Balena dashboard:

```
standard_init_linux.go:211: exec user process caused "exec format error"
Service exited 'rpiplay sha256:<redacted>'
Restarting service 'rpiplay sha256:<redacted>'
```

I can't access the `rpiplay` terminal (also repeating over and over again, except for the first line):

```
Connecting to <redacted>...
Spawning shell...
Error response from daemon: Container <redacted> is restarting, wait until the container is running
Error response from daemon: Container <redacted> is restarting, wait until the container is running
SSH session disconnected
SSH reconnecting...
```

What can be wrong here? How to fix it?

(Note: I'm completely new to balenaCloud; apologies upfront if I make a rookie mistake)

**Comment by rahul-thakoor** [comment]
Hello,

Thanks for trying the project!

Can you please share more details on how you deployed the app? The err looks like an architecture incompatibility.

- Which device-type are you using for your fleet?
- Are you using Raspberry Pi 3 32-bit or 64-bit OS image?

**Comment by pro-sumer** [comment]
Initially I tried joining the balenaHub openFleet without creating an account. That got me to seeing an AirPlay receiver on all of my Apple devices, but none could connect to it. Since I did not know whether I could check any logs, and wanted to learn more about balenaCloud anyway, I decided to try the second suggested path as well. I created an account, installed balenaOS 2.83.21+rev1 (without even noticing that there are 32-bits and 64-bits versions) and used your "1 click" button. Since this attempt did not result in seeing an AirPlay receiver on any device I looked at the logs, which are the ones I posted in this issue.

* My dashboard displays my Pi as "Raspberry Pi 3"
* I have no idea which OS image I installed and I can't see it on my dashboard either...

**Comment by pro-sumer** [comment]
Looks like the default balenaOS is 32-bits.

Should I try the alternative 64-bits version?

(Which one does RPiPlay need?)

**Comment by tecandrew** [comment]
yup, seeing this issue too. running on `pi zero w`. something exec prob isn't compatible 

```
=============================================================
    Welcome to balenaOS
=============================================================
root@86945f1:~# lscpu
Architecture:        armv6l
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
Vendor ID:           ARM
Model:               7
Model name:          ARM1176
Stepping:            r0p7
CPU max MHz:         1000.0000
CPU min MHz:         700.0000
BogoMIPS:            897.37
Flags:               half thumb fastmult vfp edsp java tls
root@86945f1:~# uname -a
Linux 86945f1 5.10.31 #1 Fri Apr 23 15:16:49 UTC 2021 armv6l armv6l armv6l GNU/Linux
```

**Comment by rahul-thakoor** [comment]
I was able to reproduce it. Looking into it. Thanks for reporting

**Comment by rahul-thakoor** [comment]
hey @tecandrew @pro-sumer I added a fix. Can you please deploy the app with the latest changes? 
Cheers

**Comment by tecandrew** [comment]
looks like the service executes now (no error message) and I can see it on my network. does mirror anything, but might be because i'm running development OS or the pi zero can't keep up  

![image](https://user-images.githubusercontent.com/21319730/145100536-a3615afc-83a5-4bda-84c5-fefea41be100.jpeg)

**Comment by rahul-thakoor** [comment]
Hi @tecandrew you have to use screen mirroring from the control center. Casting music only is not supported. If you want to only play music please consider balenaSound.
