### ISSUE TITLE
aacDecoder_DecodeFrame error : 0x4002/0x400c

### ISSUE THREAD

**Issue by pro-sumer** [rahul-thakoor/balena-rpiplay#18]
Thank you for solving #16!

With this fix I now indeed see a RPiPlay AirPlay receiver on my iOS devices.

However, I'm unable to stream any video to it. Instead my log fills up with either of these two lines:

* `rpiplay  aacDecoder_DecodeFrame error : 0x4002`
* `rpiplay  aacDecoder_DecodeFrame error : 0x400c`

Sources tried:
* Disney+ (on iPad running iOS 15.2 RC)
* Home made video in VLC (on same iPad)
* Apple TV+ (on iPhone running iOS 14.8.1)

Setup:
* Raspberry Pi 3 Model B Vi.2
* balenaOS 2.83.21+rev1
* wired network

Hope you can fix this too!

**Comment by rahul-thakoor** [comment]
Please see https://github.com/rahul-thakoor/balena-rpiplay/issues/5

can you confirm you are using screen mirroring from control center and not trying to cast directly please?

**Comment by pro-sumer** [comment]
Unfortunately I can confirm that I was _not_ screen mirroring from the Control Center...

I did not know about this limitation (bummer). Will try to test again tonight.

**Comment by pro-sumer** [comment]
Now that I tried screen mirroring instead of casting results are indeed different:

* Disney+: HDCP error
* Home made video in VLC: screen remains black, no audio
* Apple TV+: cannot play movie, because the connected display is not authorised to play protected movies

However, home made videos in Infuse do work! Although quite impressive, not my use case.

Probably will have to buy yet another Apple TV anyway...
