### ISSUE TITLE
Pi Zero 2 Support

### ISSUE THREAD

**Issue by dedSyn4ps3** [rahul-thakoor/balena-rpiplay#19]
### **Salutations!**

I've recently noticed this project while flashing something onto a USB drive and thought I would check it out, as _I have recently been looking to implement such a thing for a tech-illiterate family member_.

**I recently snagged a couple of the new Zero 2 W's, and was just curious if there are plans to add an additional option for device images to accommodate this new board to utilize the Cortex-A53 that is has.** If not, would you consider making the changes to add a new image for this board?

**Many Thanks!**

**Comment by rahul-thakoor** [comment]
Hello :)

Sure, I will add this as soon as I get a chance 👍
